export enum EmailType {
  TEACHER_CHANGE_EMAIL = 'TEACHER_CHANGE_EMAIL',
  CONTACT_INVITE = 'CONTACT_INVITE',
  CONTACT_RESET_PASSWORD = 'CONTACT_RESET_PASSWORD',
  CONTACT_NOTIFY_PRIVATE_PRACTICE_FINISHED = 'CONTACT_NOTIFY_PRIVATE_PRACTICE_FINISHED',
  CONTACT_NOTIFY_BOOKED_LESSON_FINISHED = 'CONTACT_NOTIFY_BOOKED_LESSON_FINISHED',
  PAYMENT_INVOICE = 'PAYMENT_INVOICE',
  PAYMENT_ORDER = 'PAYMENT_ORDER',
  PROMOCODE = 'PROMOCODE',
  CONTACT_US_FORM = 'CONTACT_US_FORM',
  CONTACT_US_REPLY = 'CONTACT_US_REPLY',
  BETA_TESTING_REPLY = 'BETA_TESTING_REPLY',
  TEACHER_REGISTRATION_FORM = 'TEACHER_REGISTRATION_FORM',
  STUDENT_WELCOME = 'STUDENT_WELCOME',
  PARTNER_WELCOME = 'PARTNER_WELCOME',
  ACCOUNTING_REPORT = 'ACCOUNTING_REPORT'
}
